
# Supabase configuration
project_id = "lomogmjwjnhvmcqkpjmg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[functions]
[functions.create-checkout]
verify_jwt = true
[functions.verify-payment]
verify_jwt = true
[functions.cmi-payment]
verify_jwt = true
[functions.stripe-webhook]
verify_jwt = false
[functions.log-security-event]
verify_jwt = true
[functions.check-server-status]
verify_jwt = true
[functions.stripe-config]
verify_jwt = true
[functions.setup-backups]
verify_jwt = true
[functions.disaster-recovery-check]
verify_jwt = true
[functions.request-data-export]
verify_jwt = true
[functions.request-account-deletion]
verify_jwt = true
