// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lomogmjwjnhvmcqkpjmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvbW9nbWp3am5odm1jcWtwam1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5Nzk5MjAsImV4cCI6MjA2MDU1NTkyMH0.VN3QYobWqUK0mDBVWYuVc_bdjAFcEla4s9D_opyxz4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);