// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rseknjcrtpnlmasljwmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzZWtuamNydHBubG1hc2xqd21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDQwOTcsImV4cCI6MjA2MDQ4MDA5N30._QsLBLTWhC554tCDjHe9K-aPXysmO5yLH-G4xGWrr_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);